import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY


def generate_legal_notice_pdf(
    applicable_law: str,
    complaint_text: str,
    user_language: str = "English",
    complainant_name: str = "Complainant",
    respondent_name: str = "Respondent",
    complainant_address: str = "",
    respondent_address: str = "",
) -> bytes:
    """
    Generate a formatted 'Legal Notice / Formal Complaint' PDF using ReportLab.

    Returns the PDF as bytes so it can be streamed directly in a FastAPI response.
    """
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2.5 * cm,
        leftMargin=2.5 * cm,
        topMargin=2.5 * cm,
        bottomMargin=2.5 * cm,
    )

    styles = getSampleStyleSheet()

    # --- Custom styles ---
    title_style = ParagraphStyle(
        "NoticeTitle",
        parent=styles["Heading1"],
        fontSize=16,
        textColor=colors.HexColor("#1a237e"),
        alignment=TA_CENTER,
        spaceAfter=6,
        fontName="Helvetica-Bold",
    )

    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#555555"),
        alignment=TA_CENTER,
        spaceAfter=4,
    )

    section_heading_style = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontSize=11,
        textColor=colors.HexColor("#1a237e"),
        spaceBefore=12,
        spaceAfter=4,
        fontName="Helvetica-Bold",
    )

    body_style = ParagraphStyle(
        "BodyText",
        parent=styles["Normal"],
        fontSize=10,
        leading=16,
        alignment=TA_JUSTIFY,
        spaceAfter=6,
    )

    label_style = ParagraphStyle(
        "Label",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.HexColor("#777777"),
    )

    disclaimer_style = ParagraphStyle(
        "Disclaimer",
        parent=styles["Normal"],
        fontSize=8,
        textColor=colors.HexColor("#888888"),
        alignment=TA_CENTER,
        leading=12,
    )

    # --- Build document elements ---
    elements = []

    # Header bar (simulated with a coloured table)
    header_data = [[Paragraph("⚖ NyayBot — AI Legal Assistant for India", ParagraphStyle(
        "HeaderText",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.white,
        fontName="Helvetica-Bold",
        alignment=TA_CENTER,
    ))]]
    header_table = Table(header_data, colWidths=[doc.width])
    header_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#1a237e")),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ("RIGHTPADDING", (0, 0), (-1, -1), 12),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.HexColor("#1a237e")]),
    ]))
    elements.append(header_table)
    elements.append(Spacer(1, 0.4 * cm))

    # Document title
    elements.append(Paragraph("LEGAL NOTICE / FORMAL COMPLAINT", title_style))
    elements.append(Paragraph(
        f"Generated by NyayBot on {datetime.now().strftime('%d %B %Y')} | Language: {user_language}",
        subtitle_style,
    ))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#1a237e")))
    elements.append(Spacer(1, 0.3 * cm))

    # Parties section
    elements.append(Paragraph("PARTIES", section_heading_style))

    parties_data = [
        [
            Paragraph("<b>COMPLAINANT (Sender)</b>", label_style),
            Paragraph("<b>RESPONDENT (Recipient)</b>", label_style),
        ],
        [
            Paragraph(complainant_name or "—", body_style),
            Paragraph(respondent_name or "—", body_style),
        ],
        [
            Paragraph(complainant_address or "Address: —", body_style),
            Paragraph(respondent_address or "Address: —", body_style),
        ],
    ]
    parties_table = Table(parties_data, colWidths=[doc.width / 2, doc.width / 2])
    parties_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#dddddd")),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e8eaf6")),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(parties_table)
    elements.append(Spacer(1, 0.3 * cm))

    # Applicable law
    elements.append(Paragraph("APPLICABLE LAW / LEGAL BASIS", section_heading_style))
    elements.append(Paragraph(applicable_law, body_style))

    # Complaint / problem description
    elements.append(Paragraph("DESCRIPTION OF GRIEVANCE", section_heading_style))
    # Split on newlines to preserve formatting
    for para in complaint_text.split("\n"):
        stripped = para.strip()
        if stripped:
            elements.append(Paragraph(stripped, body_style))

    # Relief sought
    elements.append(Paragraph("RELIEF SOUGHT", section_heading_style))
    elements.append(Paragraph(
        "The Complainant requests the Respondent to take immediate corrective action, "
        "failing which the Complainant reserves the right to approach the competent "
        "authority / court / consumer forum / labour commissioner as applicable under the "
        "laws cited above.",
        body_style,
    ))

    # Signature area
    elements.append(Spacer(1, 0.8 * cm))
    sig_data = [
        [
            Paragraph("Date: " + datetime.now().strftime("%d/%m/%Y"), body_style),
            Paragraph("Signature: ___________________________", body_style),
        ],
        [
            Paragraph("", body_style),
            Paragraph(complainant_name or "Complainant", body_style),
        ],
    ]
    sig_table = Table(sig_data, colWidths=[doc.width / 2, doc.width / 2])
    sig_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(sig_table)

    # Divider and footer
    elements.append(Spacer(1, 0.5 * cm))
    elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#aaaaaa")))
    elements.append(Spacer(1, 0.2 * cm))
    elements.append(Paragraph(
        "Free Legal Aid: Call NALSA at <b>15100</b> | Find your nearest DLSA at <b>nalsa.gov.in</b><br/>"
        "NyayBot provides legal information, not legal advice. "
        "Always verify with your nearest District Legal Services Authority (DLSA).",
        disclaimer_style,
    ))

    doc.build(elements)
    return buffer.getvalue()
